groups:
  - name: tgworker.alerts
    interval: 1m
    rules:
      - alert: TelegramSessionsZero
        expr: tgworker_sessions_authorized < 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Нет активных Telegram-сессий"
          description: "tgworker не имеет ни одной авторизованной сессии более 5 минут. Проверьте логин QR и статус tgworker."
      - alert: TelegramWorkerErrors
        expr: increase(tgworker_events_errors_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Ошибки tgworker"
          description: "tgworker зарегистрировал ошибки Telethon или вебхуков за последние 5 минут. Изучите логи tgworker."
