name: Deploy on push to main
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          set -eu
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts
      - name: Remote deploy
        run: |
          set -eux
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" "bash /opt/avio/deploy.sh"
