name: Telegram smoke tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt pytest
      - name: Run Telegram smoke tests
        env:
          WEBHOOK_SECRET: test-secret
        run: |
          python -m pytest app/tests/test_public_tg.py -vv
